version: "3.8"
services:
  postgresql:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_db
    networks:
      - default-network
    ports:
      - "5432:5432"

networks:
  default-network:
    driver: bridge
    name: default-network
